### PR TITLE
fix: Fix self.algorithms data type

### PR DESCRIPTION
**Pull request by fuh**
Requires list data type

### CODE REVIEW

**Comment by fuh** [comment]
jwt.decode() method  in PyJWT  requires a list data type.
```python
def decode(
        self,
        jwt: str,
        key: str = "",
        algorithms: Optional[List[str]] = None,
        options: Optional[Dict] = None,
        **kwargs,
    ) -> Dict[str, Any]:
```

**Comment by ffyuanda** [comment]
@fuh uhhhh, sure!

Though digging into the source dependencies, the signature suggests it could be `[Any | None]`.
```python
def _verify_signature(
        self,
        signing_input,
        header,
        signature,
        key="",
        algorithms=None,
    )
```
But yeah, let's go ahead and change it to a list.
Though you might want to test things out using `$CASDOOR_PYTHON_SDK/src/tests/test_oauth.py`,
you should set up your own Casdoor instance to test it.

This repo is lack of maintenance, if you see anything suspicious, we might be able to try to work through it :)

**Comment by hsluoyz** [comment]
@fuh @ffyuanda is this PR ready to merge?

**Comment by ffyuanda** [comment]
@hsluoyz LGTM

**Comment by hsluoyz** [comment]
@fuh can you also fix this? https://github.com/casdoor/casdoor-python-sdk/issues/10

**Comment by hsluoyz** [comment]
@fuh can you resolve the conflicts?

image

**Comment by hsluoyz** [comment]
@Steve0x2a can you make a PR to fix it?

**Pull request closed without merging**
