### PR TITLE
chore: setup.cfg and pyproject.toml added

### PR DESCRIPTION
**Pull request by ffyuanda**
Signed-off-by: ffyuanda <shaoxuan.yuan02@gmail.com>

### CODE REVIEW

**Comment by ffyuanda** [comment]
@hsluoyz please review

**Comment by ffyuanda** [comment]
> @Kininaru please review

dude you are a real problem

**Comment by ffyuanda** [comment]
@casbin-bot dude you are a real problem

**Comment by hsluoyz** [comment]
@ffyuanda any update?

**Comment by ffyuanda** [comment]
@hsluoyz I guess we need a separate repo for SDK example?

**Comment by ffyuanda** [comment]
@hsluoyz Updated to use `setup.cfg` for packaging.

**Comment by hsluoyz** [comment]
> @hsluoyz I guess we need a separate repo for SDK example?

@ffyuanda created: https://github.com/casdoor/casdoor-python-sdk-example please make PR to this repo

**Comment by hsluoyz** [comment]
@ffyuanda your code is missing `setup.py`, which is necessary for publishing: https://packaging.python.org/guides/distributing-packages-using-setuptools/

Can you first try to release it to pypi-test: https://test.pypi.org/ with a different name? Like ffyuanda-sdk? And make sure it works?

**Comment by ffyuanda** [comment]
@hsluoyz I believe now `setuptools` is trying to [transition ](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#transitioning-from-setup-py-to-setup-cfg)from `setup.py` to `setup.cfg`.

And yeah I will upload it to PyPi test later today to see the result.

**Comment by hsluoyz** [comment]
@ffyuanda ok, can you give me a guide link to publish with setup.cfg?

**Pull request merged**
